
CREATE TABLE [dbo].[BaseMaterial] (
    [MaterialId] INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
    [MaterialName] VARCHAR(255) NOT NULL,
    [MaterialCode] VARCHAR(255) NOT NULL,
    [ActivityDescription] VARCHAR(255),
    [VATRate] INT,
    [Quantity] INT,
    [Measure] VARCHAR(255),
    [LedgerAccountNumber] INT,
    [Rounding] INT,
    [ITJ_SZTJ] VARCHAR(255),
    [MaterialGroupId] INT,
    [Note] TEXT,
    [Kilojule] DECIMAL(10,2),
    [Protein] DECIMAL(10,2),
    [Fat] DECIMAL(10,2),
    [Carbohydrate] DECIMAL(10,2),
    [Cholesterol] DECIMAL(10,2),
    [Sugar] DECIMAL(10,2),
    [Salt] DECIMAL(10,2),
    [SaturatedFat] DECIMAL(10,2),
    [TransFat] DECIMAL(10,2),
    [Fiber] DECIMAL(10,2),
    [Kalcium] DECIMAL(10,2),
    [Kalium] DECIMAL(10,2),
    [CostPrice] DECIMAL(10,2),
    [RetailPrice] DECIMAL(10,2),
    [SupplierCode] VARCHAR(255)
    FOREIGN KEY ([MaterialGroupId]) REFERENCES [dbo].[MaterialGroup]([GroupCode])
);
