// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Models.Models;

public partial class AllergenMaterialView
{
    public int AllergenMaterialId { get; set; }

    public int MaterialId { get; set; }

    public string AllergenCode { get; set; }

    public string AllergenName { get; set; }

    public string AllergenDescription { get; set; }
}