// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Models.Models;

public partial class Allergen
{
    public int AllergenId { get; set; }

    public string AllergenName { get; set; }

    public string AllergenDescription { get; set; }

    public string AllergenCode { get; set; }

    public virtual ICollection<AllergenMaterial> AllergenMaterials { get; set; } = new List<AllergenMaterial>();
}