// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Models.Models;

public partial class AllergenMaterial
{
    public int AllergenMaterialId { get; set; }

    public int MaterialId { get; set; }

    public int AllergenId { get; set; }

    public virtual Allergen Allergen { get; set; }

    public virtual BaseMaterial Material { get; set; }
}