// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Models.Models;

public partial class BaseMaterial
{
    public int MaterialId { get; set; }

    public string MaterialCode { get; set; }

    public string ActivityDescription { get; set; }

    public int? Vatrate { get; set; }

    public decimal? Quantity { get; set; }

    public int? LedgerAccountNumber { get; set; }

    public int? Rounding { get; set; }

    public string ItjSztj { get; set; }

    public string MaterialGroupName { get; set; }

    public int? MaterialGroupId { get; set; }

    public string Note { get; set; }

    public decimal? CostPrice { get; set; }

    public decimal? RetailPrice { get; set; }

    public string SupplierCode { get; set; }

    public virtual ICollection<AllergenMaterial> AllergenMaterials { get; set; } = new List<AllergenMaterial>();

    public virtual ICollection<Ecode> Ecodes { get; set; } = new List<Ecode>();

    public virtual ICollection<Stock> Stocks { get; set; } = new List<Stock>();

    public virtual ICollection<Vitamin> Vitamins { get; set; } = new List<Vitamin>();
}