// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Models.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Models.Models
{
    public partial class DataBaseContext
    {
        private IDataBaseContextProcedures _procedures;

        public virtual IDataBaseContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new DataBaseContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IDataBaseContextProcedures GetProcedures()
        {
            return Procedures;
        }

        protected void OnModelCreatingGeneratedProcedures(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<GetDayMenuMacroDataResult>().HasNoKey().ToView(null);
            modelBuilder.Entity<GetMealMacroDataResult>().HasNoKey().ToView(null);
        }
    }

    public partial class DataBaseContextProcedures : IDataBaseContextProcedures
    {
        private readonly DataBaseContext _context;

        public DataBaseContextProcedures(DataBaseContext context)
        {
            _context = context;
        }

        public virtual async Task<List<GetDayMenuMacroDataResult>> GetDayMenuMacroDataAsync(int? DayMenuId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "DayMenuId",
                    Value = DayMenuId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<GetDayMenuMacroDataResult>("EXEC @returnValue = [dbo].[GetDayMenuMacroData] @DayMenuId", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<GetMealMacroDataResult>> GetMealMacroDataAsync(int? MealId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "MealId",
                    Value = MealId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<GetMealMacroDataResult>("EXEC @returnValue = [dbo].[GetMealMacroData] @MealId", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
