// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Models.Models;

public partial class DayMenu
{
    public int DayMenuId { get; set; }

    public string DayMenuName { get; set; }

    public DateTime DayMenuDate { get; set; }

    public int BreakfastId { get; set; }

    public int BrunchId { get; set; }

    public int LunchId { get; set; }

    public int AfternoonSnackId { get; set; }

    public int DinnerId { get; set; }
}