// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Models.Models;

public partial class DayOrder
{
    public int DayOrderId { get; set; }

    public bool WantBreakfast { get; set; }

    public bool WantBrunch { get; set; }

    public bool WantLunch { get; set; }

    public bool WantAfternoonSnack { get; set; }

    public bool WantDinner { get; set; }
}