// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Models.Models
{
    public partial class GetMealMacroDataResult
    {
        public int MealId { get; set; }
        [Column("TotalCostPrice", TypeName = "decimal(38,2)")]
        public decimal? TotalCostPrice { get; set; }
        [Column("TotalRetailPrice", TypeName = "decimal(38,2)")]
        public decimal? TotalRetailPrice { get; set; }
        [Column("TotalKilojule", TypeName = "decimal(38,2)")]
        public decimal? TotalKilojule { get; set; }
        [Column("TotalCalories", TypeName = "decimal(38,2)")]
        public decimal? TotalCalories { get; set; }
        [Column("TotalProtein", TypeName = "decimal(38,2)")]
        public decimal? TotalProtein { get; set; }
        [Column("TotalFat", TypeName = "decimal(38,2)")]
        public decimal? TotalFat { get; set; }
        [Column("TotalCarbohydrate", TypeName = "decimal(38,2)")]
        public decimal? TotalCarbohydrate { get; set; }
        [Column("TotalCholesterol", TypeName = "decimal(38,2)")]
        public decimal? TotalCholesterol { get; set; }
        [Column("TotalSugar", TypeName = "decimal(38,2)")]
        public decimal? TotalSugar { get; set; }
        [Column("TotalSalt", TypeName = "decimal(38,2)")]
        public decimal? TotalSalt { get; set; }
        [Column("TotalSaturatedFat", TypeName = "decimal(38,2)")]
        public decimal? TotalSaturatedFat { get; set; }
        [Column("TotalTransFat", TypeName = "decimal(38,2)")]
        public decimal? TotalTransFat { get; set; }
        [Column("TotalFiber", TypeName = "decimal(38,2)")]
        public decimal? TotalFiber { get; set; }
        [Column("TotalKalcium", TypeName = "decimal(38,2)")]
        public decimal? TotalKalcium { get; set; }
        [Column("TotalKalium", TypeName = "decimal(38,2)")]
        public decimal? TotalKalium { get; set; }
        public int HasAllergen { get; set; }
        public string Allergens { get; set; }
    }
}
