// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Models.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Models.Models
{
    public partial interface IDataBaseContextProcedures
    {
        Task<List<GetDayMenuMacroDataResult>> GetDayMenuMacroDataAsync(int? DayMenuId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetMealMacroDataResult>> GetMealMacroDataAsync(int? MealId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
