// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Models.Models;

public partial class MaterialGroup
{
    public int GroupCode { get; set; }

    public string GroupName { get; set; }

    public virtual ICollection<BaseMaterial> BaseMaterials { get; set; } = new List<BaseMaterial>();
}