// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Models.Models;

public partial class MealRecipe
{
    public int MealRecipeId { get; set; }

    public int RecipeId { get; set; }

    public int MealId { get; set; }

    public double Quantity { get; set; }
}