// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Models.Models;

public partial class Meal
{
    public int MealId { get; set; }

    public string MealName { get; set; }

    public int? ServingCount { get; set; }

    public string MealDescription { get; set; }
}