// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Models.Models;

public partial class OrderWeekMenu
{
    public int OrderWeekMenuId { get; set; }

    public int OrderId { get; set; }

    public int WeekMenuId { get; set; }
}