// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Models.Models;

public partial class RecipeCategory
{
    public int RecipeCategoryId { get; set; }

    public string CategoryName { get; set; }

    public string Description { get; set; }
}