// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Models.Models;

public partial class Vitamin
{
    public int VitaminId { get; set; }

    public int MaterialId { get; set; }

    public int? VitaminA { get; set; }

    public int? VitaminC { get; set; }

    public int? VitaminD { get; set; }

    public int? VitaminE { get; set; }

    public int? VitaminK { get; set; }

    public int? Pha { get; set; }

    public int? Fiber { get; set; }
}