// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Models.Models;

public partial class WeekMenuGenerateDataAllergen
{
    public int WeekMenuGenerateDataAllergenId { get; set; }

    public int WeekMenuGenerateDataId { get; set; }

    public int AllergenId { get; set; }
}