// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Models.Models;

public partial class WeekMenu
{
    public int WeekMenuId { get; set; }

    public string WeekMenuName { get; set; }

    public DateTime WeekMenuStartDate { get; set; }

    public DateTime WeekMenuEndDate { get; set; }

    public int MondayId { get; set; }

    public int TuesdayId { get; set; }

    public int WednesdayId { get; set; }

    public int ThursdayId { get; set; }

    public int FridayId { get; set; }

    public int SaturdayId { get; set; }

    public int SundayId { get; set; }
}