// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Models.Models;

public partial class WeekOrder
{
    public int WeekOrderId { get; set; }

    public int CustomerId { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime EndDate { get; set; }

    public int MondayTypeId { get; set; }

    public int TuesdayTypeId { get; set; }

    public int WednesdayTypeId { get; set; }

    public int ThursdayTypeId { get; set; }

    public int FridayTypeId { get; set; }

    public int SaturdayTypeId { get; set; }

    public int SundayTypeId { get; set; }
}