// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Models.Models;

public partial class WeekMenuGenerateDatum
{
    public int WeekMenuGenerateDataId { get; set; }

    public int WeekMenuId { get; set; }

    public int AgeCategoryId { get; set; }
}