/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,ts}"],
  prefix: "tw-",
  theme: {
    extend: {},

    plugins: [],
  },
  safelist: [
    // "grid",
    // "grid-cols-1",
    // "grid-cols-2",
    // "grid-cols-3",
    // "grid-cols-4",
    // "gap-4",
    // "flex",
    // "justify-center",
    // "block",
    // "p-6",
    // "rounded-lg",
    // "text-center",
    // "mb-5",
    // "text-900",
    // "text-5xl",
    // "font-medium",
    // "text-3xl",
    // "text-600",
    // "line-height-3",
    // "no-underline",
    // "ml-2",
    // "text-blue-500",
    // "cursor-pointer",
    // "w-40",
    // "w-full",
    // "mb-3",
    // "align-items-center",
    // "justify-content-between",
    // "bg-red-500",
    // "col-span-2",
  ],
};
