CREATE VIEW [dbo].[IngredientDataView]
AS SELECT 
	[Ingredient].[IngredientId]
	,[Ingredient].[RecipeId]
	,[Ingredient].[BaseMaterialId]
	,[Ingredient].[Quantity]
	,[Material].[MaterialCode]
	,[Material].[MaterialName]
	,[Material].[Note]
	,[Material].[MaterialGroupId]
	,[MaterialGroup].[GroupCode]
	,[MaterialGroup].[GroupName]
	--,[AllergenMaterial].[AllergenMaterialID]
	--,[AllergenMaterial].[MaterialID]
	--,[Allergen].[AllergenCode]
	--,[Allergen].[AllergenName]
	--,[Allergen].[AllergenDescription]
	FROM [Ingredient]
	LEFT JOIN [dbo].[BaseMaterial] AS [Material] ON [Ingredient].[BaseMaterialId] = [Material].[MaterialId]
	LEFT JOIN [dbo].[MaterialGroup] AS [MaterialGroup] ON [Material].[MaterialGroupId] = [MaterialGroup].[GroupCode]
	--LEFT JOIN [dbo].[AllergenMaterial] AS [AllergenMaterial] ON [Material].[MaterialId] = [AllergenMaterial].[MaterialId]
	--LEFT JOIN [dbo].[Allergen] AS [Allergen] ON [AllergenMaterial].[AllergenId] = [Allergen].[AllergenId]